# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - monorepo-test-app-service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: npm install, build, and test
        run: |
          yarn install
          yarn build

      - name: Cleanup web cache
        working-directory: apps/web
        run: |
          rm -rf .next/cache
          rm -rf node_modules
          cp -r ../../node_modules .
          echo 'Post copy'
          ls -alh
          ls -alh node_modules

      - name: Zip artifact
        run: |
          du -sh
          du -sh node_modules
          ls -alh
          zip -qr app.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Unzip artifact
        run: |
          ls -alh
          unzip -qo app.zip
          rm app.zip
          ls -alh
          ls -alh node_modules/tsconfig
          du -sh

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "monorepo-test-app-service"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_33F4AD259C204ADD883CAC32724964AB }}
          package: .
